# Generated by Django 4.2.28 on 2026-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('new', 'New Application'), ('initial', 'Initial Screening'), ('demo', 'Demo Evaluation'), ('endorsement', 'Client Endorsement'), ('onboarding', 'Onboarding'), ('approved', 'Approved'), ('withdrawn', 'Withdrawn')], default='new', max_length=50),
        ),
    ]
