# Generated by Django 4.2.28 on 2026-04-26 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ats_new', '0002_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Initial Screening', 'Initial Screening'), ('Demo Evaluation', 'Demo Evaluation'), ('Training', 'Training'), ('Onboarding', 'Onboarding'), ('Approved', 'Approved'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ats_new.applicant')),
            ],
            options={
                'verbose_name_plural': 'Status Histories',
                'ordering': ['created_at'],
            },
        ),
    ]
