# Generated by Django 4.2.28 on 2026-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_new', '0003_alter_applicant_status_statushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='teaching_account',
            field=models.CharField(blank=True, choices=[('Vietnamese', 'Vietnamese Account'), ('Chinese', 'Chinese Account'), ('Mongolian', 'Mongolian Account')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='teaching_account_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
