# Generated by Django 4.2.28 on 2026-05-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_new', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='video_call_log',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
