# Generated by Django 4.2.28 on 2026-07-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats_new', '0013_alter_applicant_teaching_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['created_at'], 'verbose_name': 'Activity log', 'verbose_name_plural': 'Activity log'},
        ),
    ]
