# Generated by Django 4.2.28 on 2026-07-13 04:23

from django.db import migrations, models
import django.db.models.deletion


def create_initial_placements(apps, schema_editor):
    Placement = apps.get_model('ats_new', 'Placement')
    Placement.objects.get_or_create(name='Vietnamese Account', slug='Vietnamese')
    Placement.objects.get_or_create(name='Chinese Account', slug='Chinese')
    Placement.objects.get_or_create(name='Direct Account', slug='Direct')


class Migration(migrations.Migration):

    dependencies = [
        ('ats_new', '0015_statushistory_changed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(create_initial_placements),
        migrations.AlterField(
            model_name='applicant',
            name='teaching_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='ats_new.placement'),
        ),
    ]
